### ISSUE TITLE
New-ConfigurationFiles.ps1: Group counter stops at 10

### ISSUE THREAD

**Issue by randomnote1** [hmscott4/AlertManagement#25]
When `New-ConfigurationFiles.ps1` generates the `assign.alert.confg` file, the group counter stops at 10.

**Comment by shutchomatic** [comment]
<?xml version="1.0" encoding="utf-8"?>
<config version="2.0">
  <exceptions>
  </exceptions>
  <assignments>
    <assignment ID="1" Name="ADDS" Owner="Active Directory Team" enabled="true" />
    <assignment ID="2" Name="Exchange" Owner="Exchange Team" enabled="true" />
    <assignment ID="3" Name="Monitoring" Owner="Monitoring Team" enabled="true">
      <ManagementPack Name="Microsoft.SystemCenter.2007" />
      <ManagementPack Name="Microsoft.SystemCenter.ACS.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.Advisor" />
      <ManagementPack Name="Microsoft.SystemCenter.Advisor.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.Advisor.Resources.ENU" />
      <ManagementPack Name="Microsoft.SystemCenter.Apm.Infrastructure" />
      <ManagementPack Name="Microsoft.SystemCenter.Apm.Infrastructure.Monitoring" />
      <ManagementPack Name="Microsoft.SystemCenter.Apm.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.Apm.NTServices" />
      <ManagementPack Name="Microsoft.SystemCenter.Apm.Wcf" />
      <ManagementPack Name="Microsoft.SystemCenter.Apm.Web" />
      <ManagementPack Name="Microsoft.SystemCenter.ApplicationMonitoring.360.SLA" />
      <ManagementPack Name="Microsoft.SystemCenter.ApplicationMonitoring.360.Template.Dashboards" />
      <ManagementPack Name="Microsoft.SystemCenter.ApplicationMonitoring.360.Template.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.ApplicationMonitoring.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.ClientMonitoring.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.ClientMonitoring.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.ClientMonitoring.Overrides" />
      <ManagementPack Name="Microsoft.SystemCenter.ClientMonitoring.Views.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.DataProviders.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.DataWarehouse.ApmReports.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.DataWarehouse.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.DataWarehouse.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.Datawarehouse.OLAP.Base" />
      <ManagementPack Name="Microsoft.SystemCenter.DataWarehouse.Report.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.DataWarehouse.Reports" />
      <ManagementPack Name="Microsoft.SystemCenter.DataWarehouse.ServiceLevel.Report.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.DBUpdateTask" />
      <ManagementPack Name="Microsoft.SystemCenter.GTM.Summary.Dashboard.Template" />
      <ManagementPack Name="Microsoft.SystemCenter.HtmlDashboard.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.Image.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.InstanceGroup.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.Internal.UI.Tasks" />
      <ManagementPack Name="Microsoft.SystemCenter.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.ManagementPack.Recommendations" />
      <ManagementPack Name="Microsoft.SystemCenter.NetworkDevice.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.NetworkDiscovery.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.Notifications.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.Notifications.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.NTService.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.2007" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.AM.DR.2007" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.DataAccessService" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.DefaultUser" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.Infra" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.Reports.2007" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.SummaryDashboard" />
      <ManagementPack Name="Microsoft.SystemCenter.OperationsManager.Telemetry" />
      <ManagementPack Name="Microsoft.SystemCenter.ProcessMonitoring.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.Reports.Deployment" />
      <ManagementPack Name="Microsoft.SystemCenter.RuleTemplates" />
      <ManagementPack Name="Microsoft.SystemCenter.SecureReferenceOverride" />
      <ManagementPack Name="Microsoft.SystemCenter.ServiceDesigner.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.SyntheticTransactions.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.TaskTemplates" />
      <ManagementPack Name="Microsoft.SystemCenter.Visualization.Component.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.Visualization.Configuration.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.Visualization.Internal" />
      <ManagementPack Name="Microsoft.SystemCenter.Visualization.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.Visualization.Network.Dashboard" />
      <ManagementPack Name="Microsoft.SystemCenter.Visualization.Network.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.Visualization.ServiceLevelComponents" />
      <ManagementPack Name="Microsoft.SystemCenter.WebApplication.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.WebApplicationSolutions.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.WebApplicationSolutions.Library.Resources.ENU" />
      <ManagementPack Name="Microsoft.SystemCenter.WebApplicationTest.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.WorkflowFoundation.Library" />
      <ManagementPack Name="Microsoft.SystemCenter.WSManagement.Library" />
    </assignment>
    <assignment ID="4" Name="M365" Owner="M365 Team" enabled="true" />
    <assignment ID="5" Name="NetworkServices" Owner="Network Team" enabled="true" />
    <assignment ID="6" Name="Oracle" Owner="DBA Team" enabled="true" />
    <assignment ID="7" Name="PKI" Owner="PKI Team" enabled="true" />
    <assignment ID="8" Name="SharePoint" Owner="SharePoint Team" enabled="true" />
    <assignment ID="9" Name="SQL" Owner="DBA Team" enabled="true">
      <ManagementPack Name="Microsoft.SQLServer.Core.Library" />
      <ManagementPack Name="Microsoft.SQLServer.Core.Views" />
      <ManagementPack Name="Microsoft.SQLServer.Core.WebDashboards" />
      <ManagementPack Name="Microsoft.SQLServer.IS.Windows" />
      <ManagementPack Name="Microsoft.SQLServer.IS.Windows.Views" />
      <ManagementPack Name="Microsoft.SQLServer.Overrides" />
      <ManagementPack Name="Microsoft.SQLServer.Visualization.Library" />
      <ManagementPack Name="Microsoft.SQLServer.Windows.Discovery" />
      <ManagementPack Name="Microsoft.SQLServer.Windows.Monitoring" />
      <ManagementPack Name="Microsoft.SQLServer.Windows.RunAs.Addendum" />
      <ManagementPack Name="Microsoft.SQLServer.Windows.Views" />
    </assignment>
    <assignment ID="10" Name="Unix" Owner="Linux Team" enabled="true">
      <ManagementPack Name="Microsoft.Unix.ConsoleLibrary" />
      <ManagementPack Name="Microsoft.Unix.Image.Library" />
      <ManagementPack Name="Microsoft.Unix.Library" />
      <ManagementPack Name="Microsoft.Unix.LogFile.Library" />
      <ManagementPack Name="Microsoft.Unix.Process.Library" />
      <ManagementPack Name="Microsoft.Unix.ShellCommand.Library" />
      <ManagementPack Name="Microsoft.Unix.Views" />
    </assignment>
    <assignment ID="10" Name="Virtualization" Owner="Virtualization Team" enabled="true" />
    <assignment ID="10" Name="IIS" Owner="Web Team" enabled="true" />
    <assignment ID="10" Name="Windows" Owner="Windows Team" enabled="true">
      <ManagementPack Name="Microsoft.Windows.Cluster.Library" />
      <ManagementPack Name="Microsoft.Windows.Library" />
      <ManagementPack Name="Microsoft.Windows.Server.2016.Discovery" />
      <ManagementPack Name="Microsoft.Windows.Server.2016.Monitoring" />
      <ManagementPack Name="Microsoft.Windows.Server.2016.ProcessPortMonitoring" />
      <ManagementPack Name="Microsoft.Windows.Server.ClusterSharedVolumeMonitoring" />
      <ManagementPack Name="Microsoft.Windows.Server.Html5.Dashboard" />
      <ManagementPack Name="Microsoft.Windows.Server.Library" />
      <ManagementPack Name="Microsoft.Windows.Server.NetworkDiscovery" />
      <ManagementPack Name="Microsoft.Windows.Server.Reports" />
    </assignment>
    <assignment ID="10" Name="Unassigned" Owner="Monitoring Team" enabled="true">
      <ManagementPack Name="Microsoft.Windows.Client.Library" />
      <ManagementPack Name="Microsoft.Windows.Client.NetworkDiscovery" />
      <ManagementPack Name="Microsoft.Windows.Image.Library" />
      <ManagementPack Name="ODR" />
      <ManagementPack Name="SCHSCOMGeneralOverrides" />
      <ManagementPack Name="SCHWebApplicationMP" />
      <ManagementPack Name="SCOM.Alert.Management" />
      <ManagementPack Name="SCOM.Management" />
      <ManagementPack Name="System.AdminItem.Library" />
      <ManagementPack Name="System.ApplicationLog.Library" />
      <ManagementPack Name="System.BaseliningTasks.Library" />
      <ManagementPack Name="System.Hardware.Library" />
      <ManagementPack Name="System.Health.Internal" />
      <ManagementPack Name="System.Health.Library" />
      <ManagementPack Name="System.Image.Library" />
      <ManagementPack Name="System.Library" />
      <ManagementPack Name="System.NetworkManagement.Library" />
      <ManagementPack Name="System.NetworkManagement.Monitoring" />
      <ManagementPack Name="System.NetworkManagement.Reports" />
      <ManagementPack Name="System.NetworkManagement.Templates" />
      <ManagementPack Name="System.Performance.Library" />
      <ManagementPack Name="System.Snmp.Library" />
      <ManagementPack Name="System.Software.Library" />
      <ManagementPack Name="System.Virtualization.Library" />
    </assignment>
  </assignments>
</config>
